[package]
name = "task_splitting"
version = "0.1.0"
authors = ["Maiko Mueller <maiko.mueller@web.de>"]
edition = "2018"

[dependencies]
rayon = "*"
rayon_logs = {git = "https://github.com/wagnerf42/rayon-logs"}
itertools ="*"
rand = "*"
criterion = "*"

[[bench]]
name = "merge"
harness = false
